### ISSUE TITLE
Uncaught Error: This TextEditor has been destroyed

### ISSUE THREAD

**Issue by MaikuMori** [sourcegraph/sourcegraph-atom#17]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.188.0
**System**: linux 3.18.6-1-ARCH
**Thrown From**: [sourcegraph-atom](https://github.com/sourcegraph/sourcegraph-atom) package, v0.1.1

### Stack Trace

Uncaught Error: This TextEditor has been destroyed

```
At /usr/share/atom/resources/app/src/display-buffer.js:1016

Error: This TextEditor has been destroyed
  at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (/usr/share/atom/resources/app/src/display-buffer.js:1016:15)
  at Marker.module.exports.Marker.getHeadScreenPosition (/usr/share/atom/resources/app/src/marker.js:214:33)
  at new Marker (/usr/share/atom/resources/app/src/marker.js:45:41)
  at DisplayBuffer.module.exports.DisplayBuffer.getMarker (/usr/share/atom/resources/app/src/display-buffer.js:1237:20)
  at DisplayBuffer.module.exports.DisplayBuffer.markBufferRange (/usr/share/atom/resources/app/src/display-buffer.js:1269:19)
  at TextEditor.module.exports.TextEditor.markBufferRange (/usr/share/atom/resources/app/src/text-editor.js:1329:59)
  at /home/maiku/Projects/sourcegraph-atom/lib/identifier-highlighter.coffee:80:32
  at ChildProcess.exithandler (child_process.js:740:7)
  at ChildProcess.emit (events.js:119:17)
  at maybeClose (child_process.js:1013:16)
  at Socket.<anonymous> (child_process.js:1181:11)
  at Socket.emit (events.js:116:17)
  at Pipe.close (net.js:477:12)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "project-manager",
      "autocomplete-snippets",
      "autocomplete-paths"
    ],
    "themes": [
      "seti-ui",
      "seti-monokai"
    ],
    "autoHideMenuBar": true
  },
  "sourcegraph-atom": {
    "path": "~/GoProjects/bin",
    "openMessagePanelOnError": false,
    "logStatusToConsole": true
  }
}
```

### Installed Packages

```coffee
# User
atom-jinja2, v0.5.0
autocomplete-plus, v2.6.0
color-picker, v1.5.0
go-plus, v3.3.1
go-rename, v0.3.0
highlight-selected, v0.9.1
linter, v0.12.0
linter-coffeelint, v0.2.0
linter-jshint, v0.1.0
seti-monokai, v0.3.1
seti-ui, v0.6.3
sourcegraph-atom, v0.1.1

# Dev
No dev packages
```

**Comment by MaikuMori** [comment]
Closed via 6f9e08d.
