### ISSUE TITLE
Can't get Jump To Definition To Work

### ISSUE THREAD

**Issue by christopherhesse** [sourcegraph/sourcegraph-atom#24]
Here's a log of what happened: https://gist.github.com/christopherhesse/3988d699788478b95502
My notes all start with '*' the other stuff is generally the output of the different commands.

**Comment by christopherhesse** [comment]
I restarted atom to make sure I have the newest version of atom after doing the installation and also disabled all those packages.

srclib immediately started spinning when I started it up:
     Finding list of references in file: src api list --file "/Users/christopherhesse/srclibtest/src/testpackage/test1.go"

**Comment by christopherhesse** [comment]
I also tried the Testing Srclib section here:
https://srclib.org/install/
https://gist.github.com/christopherhesse/c8d13832e5feeef80f39

I also restarted atom so I could get back to work on my normal project, which triggered a new run of srclib.  Killing atom did not kill the process, so I had to kill all src processes.

**Comment by christopherhesse** [comment]
This thing seems to have a massive number of dependencies.  My $GOPATH for just this test is 105MB.

I tried to delete rog-go to see if that would fix the problem:

* `trash src/code.google.com/p/rog-go`
* `src make`
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x28 pc=0x15c290]

goroutine 1 [running]:
sourcegraph.com/sourcegraph/makex.(*Config).modTime(0xa60a40, 0x2092e2900, 0x31, 0x0, 0x200000000, 0x0, 0x0, 0x0)
	/home/samer/src/sourcegraph.com/sourcegraph/makex/config.go:46 +0xc0
sourcegraph.com/sourcegraph/makex.(*Maker).TargetSetsNeedingBuild(0x208b8d650, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/samer/src/sourcegraph.com/sourcegraph/makex/make.go:188 +0x902
sourcegraph.com/sourcegraph/makex.(*Maker).Run(0x208b8d650, 0x0, 0x0)
	/home/samer/src/sourcegraph.com/sourcegraph/makex/make.go:238 +0x48
sourcegraph.com/sourcegraph/srclib/src.(*MakeCmd).Execute(0xa6b660, 0x208c5e180, 0x0, 0x1, 0x0, 0x0)
	/home/samer/src/sourcegraph.com/sourcegraph/srclib/src/make_cmd.go:83 +0x35e
sourcegraph.com/sourcegraph/go-flags.(*Parser).ParseArgs(0x208f97620, 0x208b7e2b0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/samer/src/sourcegraph.com/sourcegraph/go-flags/parser.go:242 +0x883
sourcegraph.com/sourcegraph/go-flags.(*Parser).Parse(0x208f97620, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/samer/src/sourcegraph.com/sourcegraph/go-flags/parser.go:137 +0xa1
sourcegraph.com/sourcegraph/srclib/src.Main(0x0, 0x0)
	/home/samer/src/sourcegraph.com/sourcegraph/srclib/src/cli.go:123 +0x53
main.main()
	/home/samer/src/sourcegraph.com/sourcegraph/srclib/cmd/src/src.go:28 +0x388

goroutine 6 [syscall]:
os/signal.loop()
	/home/samer/go/src/os/signal/signal_unix.go:22 +0x1f
created by os/signal.init.1
	/home/samer/go/src/os/signal/signal_unix.go:28 +0x3f

But it looks like it just does a segfault instead.

**Comment by christopherhesse** [comment]
So I guess that means that, aside from the poor installation experience, the actual error may be due to srclib?  Not sure how to fix that one.

**Comment by MaikuMori** [comment]
Thank you very much, I'll go trough everything tomorrow.

**Comment by MaikuMori** [comment]
The problem is upstream in `sourcegraph/srclib-go`. Seems to me it has problems with:

```Go
import (
    . "xx/xx"
)
```

syntax.

The way plugin calls srclib also could be improved but I've held back a bit due to incoming changes in `src` which should make it easier to integrate it with editor plugins such as this one.

Also it's strange that it picked up all your go packages. Did you run it in your `GOPATH`? It should be ran from your project directory and it should only pick up your current projects. The 10 minute slowdown was due to  `src` analyzing 380+ Go projects.

I'll talk to the guys over at SourceSraph and get his fixed.

Thank you for the detailed bug report, very much appreciated.


CC: @samertm , @sqs

**Comment by christopherhesse** [comment]
Nice find!

I guess I put so much output garbage in here it's hard to see what I actually did.  I created a test folder "srclibtest" so that my weird go setup would not cause confusion here, and ran it in that folder.  I use App Engine normally with go and also vendor my dependencies, so that's pretty likely to cause problems too I imagine.  I will try making two different folders for this test.

Some notes from my install experience:

1) The requirements that you have GOPATH set to install the go plugin seems weird, along with the surprise dependence on godep.  It would be really nice if it just downloaded the correct srclib plugin based on my go version or whatever, and not like 105MB of dependencies.
2) The "* srclib" icon in atom with the dark theme enabled is basically invisible
3) The docs say to go to Preferences > Packages, but I had to go to Preferences > Install to install the plugin

**Comment by christopherhesse** [comment]
* `cd src/testpackage`
* `src config`

Configuration is currently only supported at the root (top-level directory) of a repository, not in a subdirectory ("src/testpackage").

* Moved my git repo to be in "srclibtest/src/testpackage" rather than "srclibtest"
* `src config`

Running: [/Users/christopherhesse/.srclib/sourcegraph.com/sourcegraph/srclib-go/.bin/srclib-go scan --repo  --subdir .]
  --> with input {}
Running: [/Users/christopherhesse/.srclib/sourcegraph.com/sourcegraph/srclib-python/.bin/srclib-python scan --repo  --subdir .]
  --> with input {}
src SCANNERS (2)
 - sourcegraph.com/sourcegraph/srclib-go scan
 - sourcegraph.com/sourcegraph/srclib-python scan

SOURCE UNITS (1)
 - GoPackage: testpackage

CONFIG PROPERTIES (0)

* `src make`
* `atom .`
* Right-click + jump to definition

Jump to Definition: src api describe --file="/Users/christopherhesse/srclibtest/src/testpackage/test1.go" --start-byte=66 --no-examples
src api describe --file="/Users/christopherhesse/srclibtest/src/testpackage/test1.go" --start-byte=66 --no-examples: 2015/04/16 09:40:53 Failed to detect git/hg repository root dir for "."; continuing. mkdir /.srclib-cache: permission denied

**Comment by MaikuMori** [comment]
I talked with the srclib guys. There was regression introduced recently which is causing the problems you have right now. They'll fix it asap.
